development:
  adapter: redis
  url: redis:<%= ENV.fetch("REDIS_HOST") { "localhost" } %>:<%= ENV.fetch("REDIS_PORT") { "6379" } %>/1

test:
  adapter: test

production:
  adapter: redis
  url: redis:<%= ENV.fetch("REDIS_HOST") { "localhost" } %>:<%= ENV.fetch("REDIS_PORT") { "6379" } %>/1
  channel_prefix: dockerized_rails_production
